name: Move PR to In Review

on:
  pull_request:
    types: [opened]

jobs:
  move_pr_to_in_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository  # ✅ GitHub 레포지토리 가져오기
        uses: actions/checkout@v4  

      - name: Move PR to In Review in GitHub Project
        run: |
          PR_ID=$(gh pr view ${{ github.event.pull_request.number }} --json id -q ".id")
          gh api graphql -F projectId="PVT_kwDOC83TE84A0Qxl" -F itemId="$PR_ID" -F fieldId="PVTSSF_lADOC83TE84A0Qxlzgp7DJ4" -F value="df73e18b" -f query='
            mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!, $value: String!) {
              updateProjectV2ItemFieldValue(input: { projectId: $projectId, itemId: $itemId, fieldId: $fieldId, value: { singleSelectOptionId: $value } }) {
                projectV2Item {
                  id
                }
              }
            }'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
